#!/usr/bin/env bash
# Interactive setup for job-boo API keys and configuration.
set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

ENV_FILE="${1:-$HOME/.job-boo.env}"

echo -e "\n${BOLD}${CYAN}Job Boo — API Key Setup${NC}\n"
echo -e "This will create/update: ${BOLD}$ENV_FILE${NC}\n"

# Initialize or load existing
declare -A KEYS
if [ -f "$ENV_FILE" ]; then
  echo -e "${DIM}Loading existing keys from $ENV_FILE${NC}\n"
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "$key" ]] && continue
    KEYS["$key"]="$value"
  done < "$ENV_FILE"
fi

prompt_key() {
  local var_name="$1"
  local description="$2"
  local hint="${3:-}"
  local current="${KEYS[$var_name]:-}"
  local masked=""

  if [ -n "$current" ]; then
    masked="...${current: -6}"
  fi

  echo -e "  ${CYAN}$description${NC}"
  [ -n "$hint" ] && echo -e "  ${DIM}$hint${NC}"

  if [ -n "$masked" ]; then
    read -rp "  $var_name [$masked]: " value
    value="${value:-$current}"
  else
    read -rp "  $var_name: " value
  fi

  if [ -n "$value" ]; then
    KEYS["$var_name"]="$value"
  fi
  echo
}

# ── AI Provider ──────────────────────────────────────────
echo -e "${BOLD}1. AI Provider (required)${NC}\n"
prompt_key "JOB_BOO_AI_KEY" "Claude or OpenAI API key" "Claude: console.anthropic.com/settings/keys | OpenAI: platform.openai.com/api-keys"

# ── Job Sources ──────────────────────────────────────────
echo -e "${BOLD}2. Job Sources (optional — free sources work without keys)${NC}\n"
prompt_key "ADZUNA_APP_ID" "Adzuna App ID (free tier: 1000 req/month)" "Register at developer.adzuna.com"
prompt_key "ADZUNA_API_KEY" "Adzuna API key" ""
prompt_key "SERPAPI_KEY" "SerpAPI key (paid, for Google Jobs)" "serpapi.com — skip if not needed"

# ── Write env file ───────────────────────────────────────
echo -e "${BOLD}Saving to $ENV_FILE...${NC}\n"

cat > "$ENV_FILE" << ENVEOF
# Job Boo environment — generated by setup-demo-env.sh
# $(date)

# AI Provider
JOB_BOO_AI_KEY=${KEYS[JOB_BOO_AI_KEY]:-}

# Adzuna (free tier)
ADZUNA_APP_ID=${KEYS[ADZUNA_APP_ID]:-}
ADZUNA_API_KEY=${KEYS[ADZUNA_API_KEY]:-}

# SerpAPI (paid, optional)
SERPAPI_KEY=${KEYS[SERPAPI_KEY]:-}
ENVEOF

chmod 600 "$ENV_FILE"
echo -e "${GREEN}Saved!${NC}\n"

# ── Summary ──────────────────────────────────────────────
echo -e "${BOLD}Summary:${NC}"
configured=0
missing=0
for key in JOB_BOO_AI_KEY ADZUNA_APP_ID ADZUNA_API_KEY SERPAPI_KEY; do
  if [ -n "${KEYS[$key]:-}" ]; then
    echo -e "  ${GREEN}[set]${NC}     $key"
    ((configured++))
  else
    echo -e "  ${YELLOW}[missing]${NC} $key"
    ((missing++))
  fi
done
echo
echo -e "  ${GREEN}$configured configured${NC}, ${YELLOW}$missing missing${NC}"
echo

if [ -z "${KEYS[JOB_BOO_AI_KEY]:-}" ]; then
  echo -e "  ${YELLOW}Warning: AI key is required for scoring and tailoring.${NC}"
fi

echo -e "\n${DIM}To use: export \$(cat $ENV_FILE | grep -v '^#' | xargs)${NC}"
echo -e "${DIM}Or run: ./demo/run.sh --env $ENV_FILE${NC}\n"
